### ISSUE TITLE
plot() raises exception when data is loaded from HDF5 file

### ISSUE THREAD

**Issue by mm-manu** [highfestiva/finplot#109]
Found strange behavior when data is loaded from an HDF5 file.
```
EDIT:
Found the reason:
When loading from HDF5, the index of the data is Int64Index, when loading from CSV, index is RangeIndex.
df.reset_index(drop=True) solved it.
```

Code to reproduce:
 
```
import numpy as np
import pandas as pd
import finplot as fplt


def test_plot(df):
    ax = fplt.create_plot("foo")
    candles = df[['time','open','close','high','low']]
    fplt.candlestick_ochl(candles, ax=ax)
    fplt.plot(df['time'], df['close'].rolling(25).mean(), ax=ax, legend='ma-25')
    fplt.show()


df_csv = pd.read_csv("sample.csv")
df_csv["time"] = df_csv["open_time"]
df_csv = df_csv.astype({'time':'datetime64[s]'})
print("CSV DataFrame dtypes:")
print(df_csv.dtypes)
print()
print("Sample row:")
print(df_csv.head(1))
print()


df_hdf = pd.read_hdf("sample.h5", "df")
df_hdf["time"] = df_hdf["open_time"]
df_hdf = df_hdf.astype({'time':'datetime64[s]'})
print("HDF DataFrame dtypes:")
print(df_hdf.dtypes)
print()
print("Sample row:")
print(df_hdf.head(1))
print()

test_plot(df_csv)
test_plot(df_hdf)

```
The first plot (data loaded from CSV) shows up correctly, the second (data loaded from HDF5) raises an Exception.

Output:
```
CSV DataFrame dtypes:
open_time             int64
open                float64
high                float64
low                 float64
close               float64
volume                int64
time         datetime64[ns]
dtype: object

Sample row:
    open_time     open     high      low    close    volume                time
0  1606705200  18539.0  18610.0  18451.0  18610.0  72481624 2020-11-30 03:00:00

HDF DataFrame dtypes:
open_time             int64
open                float64
high                float64
low                 float64
close               float64
volume                int64
time         datetime64[ns]
dtype: object

Sample row:
    open_time     open     high      low    close    volume                time
0  1606705200  18539.0  18610.0  18451.0  18610.0  72481624 2020-11-30 03:00:00

Traceback (most recent call last):
  File "/***/bug_sample.py", line 36, in <module>
    test_plot(df_hdf)
  File "/***/bug_sample.py", line 10, in test_plot
    fplt.plot(df['time'], df['close'].rolling(25).mean(), ax=ax, legend='ma-25')
  File "/home/manu/venv_py39/lib/python3.9/site-packages/finplot/__init__.py", line 1423, in plot
    y = datasrc.y / ax.vb.yscale.scalef
  File "/home/manu/venv_py39/lib/python3.9/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/manu/venv_py39/lib/python3.9/site-packages/pandas/core/arraylike.py", line 113, in __truediv__
    return self._arith_method(other, operator.truediv)
  File "/home/manu/venv_py39/lib/python3.9/site-packages/pandas/core/series.py", line 4959, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/manu/venv_py39/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 185, in arithmetic_op
    res_values = op(lvalues, rvalues)
  File "/home/manu/venv_py39/lib/python3.9/site-packages/pandas/core/ops/invalid.py", line 53, in invalid_op
    raise TypeError(f"cannot perform {name} with this index type: {typ}")
TypeError: cannot perform __truediv__ with this index type: DatetimeArray

```
Probably not an urgent issue but I can't figure out what the problem is and I normally use HDF5 for performance reasons.
Sample data: [samples.zip](https://github.com/highfestiva/finplot/files/5793240/samples.zip)

**Comment by highfestiva** [comment]
I've had many users with this problem now, so decided to add a warning printout when using an int64index seems undesired (https://github.com/highfestiva/finplot/commit/215107160303a369f1040c2a29dc9178310ddb83).
