### ISSUE TITLE
Error when trying to execute script made with pyinstaller

### ISSUE THREAD

**Issue by lightphaser** [highfestiva/finplot#140]
Hi!

The finplot is awesome, it looks nice and works well in my program, when executed inside Python IDE. However, after I make an executable from it by pyinstaller and try to run it, I get the following error:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "[PATH-TO-PYTHON]\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\finplot\__init__.py", line 2493, in <module>
  File "site-packages\pandas\_config\config.py", line 233, in __call__
  File "site-packages\pandas\_config\config.py", line 130, in _set_option
  File "site-packages\pandas\core\config_init.py", line 644, in register_plotting_backend_cb
  File "site-packages\pandas\plotting\_core.py", line 1790, in _get_plot_backend
  File "site-packages\pandas\plotting\_core.py", line 1753, in _find_backend ValueError: Could not find plotting backend 'finplot.pdplot'. Ensure that you've installed the package providing the 'finplot.pdplot' entrypoint, or that the package has a top-level `.plot` method.[7336] Failed to execute script main
  
The 16 line in main.py has this:
import finplot as fplt

Please, can you help me what might cause this issue? Thank you!
Joseph

**Comment by highfestiva** [comment]
Seems you're missing the file `finplot/pdplot.py`, try adding it manually to your installation script.

**Comment by lightphaser** [comment]
Thank you, that solved the issue!
I expected that pyinstaller will add it automatically as it did the rest of the libs.
