### ISSUE TITLE
Error: AttributeError: module 'PySide2.QtCore' has no attribute 'QT_VERSION'

### ISSUE THREAD

**Issue by ralex1975** [highfestiva/finplot#19]
Python 3.8.3
PyQt 5.15
PySide2 5.15
PyCharm 2020.1

If i run you samples (https://github.com/highfestiva/finplot/blob/master/finplot/example-analyze.py) with Debug, i get next error:
Connected to pydev debugger (build 201.6668.115)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Python38\lib\site-packages\finplot\__init__.py", line 1587, in <module>
    qtver = '%d.%d' % (QtCore.QT_VERSION//256//256, QtCore.QT_VERSION//256%256)
AttributeError: module 'PySide2.QtCore' has no attribute 'QT_VERSION'

If i'm run without Debug - all good!

P.S: if i deleted PySide2 from Python - all, good!

**Comment by highfestiva** [comment]
Fixed in `a82deaeab893fe073b1c82738e1883b62374178b`.
