### ISSUE TITLE
IndexError occurs for coins with very low value like SHIB and PIG etc

### ISSUE THREAD

**Issue by shujaatak** [highfestiva/finplot#242]
I added **PIG** and **SHIB** to **complicated.py** example in [this line](https://github.com/highfestiva/finplot/blob/cfd2dd6e36b802f30cbaf4d9935d117cc27895b6/finplot/examples/complicated.py#L386) like this:
```
    [panel.symbol.addItem(i+'USDT') for i in 'BTC ETH XRP DOGE BNB SOL ADA LTC LINK DOT TRX BCH PIG SHIB LINA'.split()]
```
Complicated.py examples successfully works for all coins including **LINA** but when I select PIG or SHIB, the following error occurs:
```
Traceback (most recent call last):
  File "/home/shujaat/PycharmProjects/pythonProject1/chart.py", line 263, in change_asset
    df = load_price_history(symbol, interval=interval)
  File "/home/shujaat/PycharmProjects/pythonProject1/chart.py", line 135, in load_price_history
    t0 = df.index[-2].timestamp()
  File "/home/shujaat/.local/share/virtualenvs/pythonProject1-x7OYgGdL/lib/python3.9/site-packages/pandas/core/indexes/extension.py", line 279, in __getitem__
    result = self._data[key]
  File "/home/shujaat/.local/share/virtualenvs/pythonProject1-x7OYgGdL/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 322, in __getitem__
    result = super().__getitem__(key)
  File "/home/shujaat/.local/share/virtualenvs/pythonProject1-x7OYgGdL/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 194, in __getitem__
    result = self._ndarray[key]
IndexError: index -2 is out of bounds for axis 0 with size 0
```

**Comment by highfestiva** [comment]
Read the error message. It says the bug is in `File "/home/shujaat/PycharmProjects/pythonProject1/chart.py", line 135, in load_price_history`.
