### ISSUE TITLE
[BUG] for larger y-scale data (eg. OBV) corrupted after update_gfx

### ISSUE THREAD

**Issue by jonsl** [highfestiva/finplot#283]
Thanks for a great library.

I discovered that for a very small set of eg: OBV data, each iteration of `update_gfx()` can give very different plots, and can then crash.

It seems that `update_data()` works fine with the same data set.

The bug is quite difficult to reproduce, so for now I just wanted to give you the crash stack:

`
Traceback (most recent call last):
  File "/home/jonsl/dev/semble/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/AxisItem.py", line 608, in paint
    specs = self.generateDrawSpecs(painter)
  File "/home/jonsl/dev/semble/./finplot/finplot/__init__.py", line 139, in generateDrawSpecs
    specs = super().generateDrawSpecs(p)
  File "/home/jonsl/dev/semble/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/AxisItem.py", line 925, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "/home/jonsl/dev/semble/./finplot/finplot/__init__.py", line 120, in tickValues
    if not self.vb.datasrc.is_smooth_time():
  File "/home/jonsl/dev/semble/./finplot/finplot/__init__.py", line 325, in is_smooth_time
    self._smooth_time = self.timebased() and (np.abs(np.diff(self.x.values[1:100])[1:]//(self.period_ns//1000)-1000) < 10).all()
FloatingPointError: divide by zero encountered in floor_divide
`

I'm going to spend a good amount of time now to reproduce this problem.

Meanwhile:
`
finplot version:
current HEAD: 6f3ea85
Thu Nov 18 17:17:26 2021 +0100

pyqtgraph version:
pyqtgraph-0.12.3

pyqt version:
PyQt5-Qt5-5.15.2
`

Thanks again

**Comment by jonsl** [comment]
Right, this was actually what I was trying say.

And apologies the size of the data, but it only work without this (also from @pdanford for the script):

`import finplot as fplt
import pandas as pd
import io

data_0 = """time,vol
2021-11-14T03:00:00.000,  1.67423000e+05
2021-11-14T04:00:00.000,  3.51551000e+05
2021-11-14T05:00:00.000,  6.67229000e+05
2021-11-14T06:00:00.000,  1.05587800e+06
2021-11-14T07:00:00.000,  1.39308400e+06
2021-11-14T08:00:00.000,  1.07242400e+06
2021-11-14T09:00:00.000,  1.18816700e+06
2021-11-14T10:00:00.000,  1.02747200e+06
2021-11-14T11:00:00.000,  1.16886200e+06
2021-11-14T12:00:00.000,  1.16886200e+06
2021-11-14T13:00:00.000,  1.16886200e+06
2021-11-14T14:00:00.000,  1.80671800e+06
2021-11-14T15:00:00.000,  1.56993000e+05
2021-11-14T16:00:00.000, -3.41945000e+05
2021-11-14T17:00:00.000,  3.85775500e+06
2021-11-14T18:00:00.000,  2.52148300e+06
2021-11-14T19:00:00.000,  4.55817300e+06
2021-11-14T20:00:00.000,  3.60660800e+06
2021-11-14T21:00:00.000,  1.39509530e+07
2021-11-14T22:00:00.000,  1.25163590e+07
2021-11-14T23:00:00.000,  1.31609240e+07
2021-11-15T00:00:00.000,  1.44187180e+07
2021-11-15T01:00:00.000,  1.38767670e+07
2021-11-15T02:00:00.000,  1.34324620e+07
2021-11-15T03:00:00.000,  1.30013840e+07
2021-11-15T04:00:00.000,  1.22153080e+07
2021-11-15T05:00:00.000,  1.16996680e+07
2021-11-15T06:00:00.000,  1.11428060e+07
2021-11-15T07:00:00.000,  1.02846300e+07
2021-11-15T08:00:00.000,  1.10917080e+07
2021-11-15T09:00:00.000,  1.19751950e+07
2021-11-15T10:00:00.000,  1.69289380e+07
2021-11-15T11:00:00.000,  1.87277750e+07
2021-11-15T12:00:00.000,  2.08311380e+07
2021-11-15T13:00:00.000,  1.97878150e+07
2021-11-15T14:00:00.000,  1.83722800e+07
2021-11-15T15:00:00.000,  1.92766760e+07
2021-11-15T16:00:00.000,  1.84349020e+07
2021-11-15T17:00:00.000,  1.70201910e+07
2021-11-15T18:00:00.000,  1.79731170e+07
2021-11-15T19:00:00.000,  1.85551990e+07
2021-11-15T20:00:00.000,  1.81884010e+07
2021-11-15T21:00:00.000,  1.87196020e+07
2021-11-15T22:00:00.000,  1.82496730e+07
2021-11-15T23:00:00.000,  1.78816410e+07
2021-11-16T00:00:00.000,  1.72129010e+07
2021-11-16T01:00:00.000,  1.53850870e+07
2021-11-16T02:00:00.000,  1.50261020e+07
2021-11-16T03:00:00.000,  1.45285130e+07
2021-11-16T04:00:00.000,  1.49185620e+07
2021-11-16T05:00:00.000,  1.45369460e+07
2021-11-16T06:00:00.000,  1.49648830e+07
2021-11-16T07:00:00.000,  1.46749060e+07
2021-11-16T08:00:00.000,  1.52367880e+07
2021-11-16T09:00:00.000,  1.38460410e+07
2021-11-16T10:00:00.000,  1.08798530e+07
2021-11-16T11:00:00.000,  1.16802110e+07
2021-11-16T12:00:00.000,  1.11508090e+07
2021-11-16T13:00:00.000,  1.14350730e+07
2021-11-16T14:00:00.000,  1.21105480e+07
2021-11-16T15:00:00.000,  1.15638250e+07
2021-11-16T16:00:00.000,  1.18582060e+07
2021-11-16T17:00:00.000,  1.16139720e+07
2021-11-16T18:00:00.000,  1.10360030e+07
2021-11-16T19:00:00.000,  1.14750270e+07
2021-11-16T20:00:00.000,  1.09085070e+07
2021-11-16T21:00:00.000,  1.14750920e+07
2021-11-16T22:00:00.000,  1.16582500e+07
2021-11-16T23:00:00.000,  1.14147190e+07
2021-11-17T00:00:00.000,  1.08103030e+07
2021-11-17T01:00:00.000,  1.05734110e+07
2021-11-17T02:00:00.000,  1.11908360e+07
2021-11-17T03:00:00.000,  1.08496080e+07
2021-11-17T04:00:00.000,  1.09950010e+07
2021-11-17T05:00:00.000,  1.09950010e+07
2021-11-17T06:00:00.000,  9.65314800e+06
2021-11-17T07:00:00.000,  1.08220900e+07
2021-11-17T08:00:00.000,  1.06288100e+07
2021-11-17T09:00:00.000,  1.01658210e+07
2021-11-17T10:00:00.000,  1.11622740e+07
2021-11-17T11:00:00.000,  1.13749600e+07
2021-11-17T12:00:00.000,  1.10558920e+07
2021-11-17T13:00:00.000,  1.07392540e+07
2021-11-17T14:00:00.000,  1.02665590e+07
2021-11-17T15:00:00.000,  1.11156070e+07
2021-11-17T16:00:00.000,  1.18802810e+07
2021-11-17T17:00:00.000,  1.23829400e+07
2021-11-17T18:00:00.000,  1.18807320e+07
2021-11-17T19:00:00.000,  1.20936130e+07
2021-11-17T20:00:00.000,  1.25457700e+07
2021-11-17T21:00:00.000,  1.22615900e+07
2021-11-17T22:00:00.000,  1.19483110e+07
2021-11-17T23:00:00.000,  1.21001030e+07
2021-11-18T00:00:00.000,  1.23764610e+07
2021-11-18T01:00:00.000,  1.21555280e+07
2021-11-18T02:00:00.000,  1.24517420e+07
2021-11-18T03:00:00.000,  1.20824520e+07
2021-11-18T04:00:00.000,  1.18467360e+07
2021-11-18T05:00:00.000,  1.16326050e+07
2021-11-18T06:00:00.000,  1.14338480e+07
2021-11-18T07:00:00.000,  1.12117710e+07
2021-11-18T08:00:00.000,  1.05240090e+07
2021-11-18T09:00:00.000,  9.85509300e+06
2021-11-18T10:00:00.000,  1.01156490e+07
2021-11-18T11:00:00.000,  9.62283300e+06
2021-11-18T12:00:00.000,  9.10064800e+06
2021-11-18T13:00:00.000,  9.10064800e+06
2021-11-18T14:00:00.000,  8.72272500e+06
2021-11-18T15:00:00.000,  7.11044900e+06
2021-11-18T16:00:00.000,  6.30883200e+06
2021-11-18T17:00:00.000,  7.50147500e+06
2021-11-18T18:00:00.000,  7.79474100e+06
2021-11-18T19:00:00.000,  5.65067790e+07
2021-11-18T20:00:00.000,  5.41977460e+07
2021-11-18T21:00:00.000,  5.36001200e+07
2021-11-18T22:00:00.000,  5.29478830e+07
2021-11-18T23:00:00.000,  5.24435100e+07
2021-11-19T00:00:00.000,  5.31800340e+07
2021-11-19T01:00:00.000,  6.04059140e+07
2021-11-19T02:00:00.000,  5.22534020e+07
2021-11-19T03:00:00.000,  5.06794530e+07
2021-11-19T04:00:00.000,  5.14261630e+07
2021-11-19T05:00:00.000,  4.97951370e+07
2021-11-19T06:00:00.000,  5.14553690e+07
2021-11-19T07:00:00.000,  4.99166220e+07
2021-11-19T08:00:00.000,  5.09225480e+07
2021-11-19T09:00:00.000,  5.22842140e+07
2021-11-19T10:00:00.000,  5.28887820e+07
2021-11-19T11:00:00.000,  5.32861520e+07
2021-11-19T12:00:00.000,  5.48056650e+07
2021-11-19T13:00:00.000,  5.53214980e+07
2021-11-19T14:00:00.000,  5.62862800e+07
2021-11-19T15:00:00.000,  5.52755840e+07
2021-11-19T16:00:00.000,  5.63586790e+07
2021-11-19T17:00:00.000,  5.55733460e+07
2021-11-19T18:00:00.000,  5.50125610e+07
2021-11-19T19:00:00.000,  5.40499710e+07
2021-11-19T20:00:00.000,  5.36383320e+07
2021-11-19T21:00:00.000,  5.40549120e+07
2021-11-19T22:00:00.000,  5.46265960e+07
2021-11-19T23:00:00.000,  5.49160260e+07
2021-11-20T00:00:00.000,  5.54299650e+07
2021-11-20T01:00:00.000,  5.59868690e+07
2021-11-20T02:00:00.000,  5.75349210e+07
2021-11-20T03:00:00.000,  5.70765210e+07
2021-11-20T04:00:00.000,  5.66011170e+07
2021-11-20T05:00:00.000,  5.55809560e+07
2021-11-20T06:00:00.000,  5.58307730e+07
2021-11-20T07:00:00.000,  5.50264450e+07
2021-11-20T08:00:00.000,  5.56582930e+07
2021-11-20T09:00:00.000,  5.63576170e+07
2021-11-20T10:00:00.000,  5.73294620e+07
2021-11-20T11:00:00.000,  6.07446790e+07
2021-11-20T12:00:00.000,  5.92550010e+07
2021-11-20T13:00:00.000,  5.83032210e+07
2021-11-20T14:00:00.000,  5.55371980e+07
2021-11-20T15:00:00.000,  5.37184560e+07
2021-11-20T16:00:00.000,  5.47901260e+07
2021-11-20T17:00:00.000,  5.41992180e+07
2021-11-20T18:00:00.000,  5.57457410e+07
2021-11-20T19:00:00.000,  5.75228950e+07
2021-11-20T20:00:00.000,  5.81873690e+07
2021-11-20T21:00:00.000,  5.74706370e+07
2021-11-20T22:00:00.000,  5.89015630e+07
2021-11-20T23:00:00.000,  5.82848840e+07
2021-11-21T00:00:00.000,  5.92510050e+07
2021-11-21T01:00:00.000,  5.92510050e+07
2021-11-21T02:00:00.000,  5.88175400e+07
2021-11-21T03:00:00.000,  5.84205110e+07
2021-11-21T04:00:00.000,  5.79232470e+07
2021-11-21T05:00:00.000,  5.81809250e+07
2021-11-21T06:00:00.000,  5.81809250e+07
2021-11-21T07:00:00.000,  6.11190610e+07
2021-11-21T08:00:00.000,  5.78338540e+07
2021-11-21T09:00:00.000,  5.65967020e+07
2021-11-21T10:00:00.000,  5.78508320e+07
2021-11-21T11:00:00.000,  6.08920250e+07
2021-11-21T12:00:00.000,  6.17014860e+07
2021-11-21T13:00:00.000,  6.09416420e+07
2021-11-21T14:00:00.000,  6.21741210e+07
2021-11-21T15:00:00.000,  6.67579510e+07
2021-11-21T16:00:00.000,  7.07543670e+07
2021-11-21T17:00:00.000,  6.89965040e+07
2021-11-21T18:00:00.000,  6.80863920e+07
2021-11-21T19:00:00.000,  6.71398120e+07
2021-11-21T20:00:00.000,  6.83881220e+07
2021-11-21T21:00:00.000,  6.92512340e+07
2021-11-21T22:00:00.000,  6.83246980e+07
2021-11-21T23:00:00.000,  6.77495480e+07
2021-11-22T00:00:00.000,  6.67911350e+07
2021-11-22T01:00:00.000,  6.59880550e+07
2021-11-22T02:00:00.000,  6.53233070e+07
2021-11-22T03:00:00.000,  6.47552460e+07
2021-11-22T04:00:00.000,  6.42002620e+07
2021-11-22T05:00:00.000,  6.48622440e+07
2021-11-22T06:00:00.000,  6.51486710e+07
2021-11-22T07:00:00.000,  6.58239740e+07
2021-11-22T08:00:00.000,  6.60537530e+07
2021-11-22T09:00:00.000,  6.57470830e+07
2021-11-22T10:00:00.000,  6.53157010e+07
2021-11-22T11:00:00.000,  6.55831580e+07
2021-11-22T12:00:00.000,  6.51123380e+07
2021-11-22T13:00:00.000,  6.64270940e+07
2021-11-22T14:00:00.000,  6.54397210e+07
2021-11-22T15:00:00.000,  6.48422160e+07
2021-11-22T16:00:00.000,  6.53667800e+07
2021-11-22T17:00:00.000,  6.50362400e+07
2021-11-22T18:00:00.000,  6.46542560e+07
2021-11-22T19:00:00.000,  6.38503840e+07
2021-11-22T20:00:00.000,  6.31731650e+07
2021-11-22T21:00:00.000,  6.36651430e+07
2021-11-22T22:00:00.000,  6.41946190e+07
2021-11-22T23:00:00.000,  6.38570660e+07
2021-11-23T00:00:00.000,  6.41374000e+07
2021-11-23T01:00:00.000,  6.46191060e+07
2021-11-23T02:00:00.000,  6.42059640e+07
2021-11-23T03:00:00.000,  6.48093420e+07
2021-11-23T04:00:00.000,  6.59360270e+07
2021-11-23T05:00:00.000,  6.53246540e+07
2021-11-23T06:00:00.000,  6.48636070e+07
2021-11-23T07:00:00.000,  6.42165360e+07
2021-11-23T08:00:00.000,  6.37216070e+07
2021-11-23T09:00:00.000,  6.46901550e+07
2021-11-23T10:00:00.000,  6.34227280e+07
2021-11-23T11:00:00.000,  6.29677490e+07
2021-11-23T12:00:00.000,  6.24750370e+07
2021-11-23T13:00:00.000,  6.29721960e+07
2021-11-23T14:00:00.000,  6.39665980e+07
2021-11-23T15:00:00.000,  6.32065140e+07
2021-11-23T16:00:00.000,  6.34573860e+07
2021-11-23T17:00:00.000,  6.31142780e+07
2021-11-23T18:00:00.000,  6.28908590e+07
2021-11-23T19:00:00.000,  6.32496540e+07
2021-11-23T20:00:00.000,  6.35511600e+07
2021-11-23T21:00:00.000,  6.30879770e+07
2021-11-23T22:00:00.000,  6.27857370e+07
2021-11-23T23:00:00.000,  6.31574360e+07
2021-11-24T00:00:00.000,  6.34881450e+07
2021-11-24T01:00:00.000,  6.16801420e+07
2021-11-24T02:00:00.000,  6.04521330e+07
2021-11-24T03:00:00.000,  5.89244120e+07
2021-11-24T04:00:00.000,  5.95634800e+07
2021-11-24T05:00:00.000,  5.92604180e+07
2021-11-24T06:00:00.000,  5.95984490e+07
2021-11-24T07:00:00.000,  5.85518940e+07
2021-11-24T08:00:00.000,  5.97760750e+07
2021-11-24T09:00:00.000,  6.03643480e+07
2021-11-24T10:00:00.000,  5.98140650e+07
2021-11-24T11:00:00.000,  6.02218270e+07
2021-11-24T12:00:00.000,  5.95607240e+07
2021-11-24T13:00:00.000,  5.86459220e+07
2021-11-24T14:00:00.000,  5.76493250e+07
2021-11-24T15:00:00.000,  5.86001260e+07
2021-11-24T16:00:00.000,  5.80052110e+07
2021-11-24T17:00:00.000,  5.75814990e+07
2021-11-24T18:00:00.000,  5.78730480e+07
2021-11-24T19:00:00.000,  5.77124540e+07
2021-11-24T20:00:00.000,  5.80635890e+07
2021-11-24T21:00:00.000,  5.76141410e+07
2021-11-24T22:00:00.000,  5.86801510e+07
2021-11-24T23:00:00.000,  5.90216870e+07
2021-11-25T00:00:00.000,  5.98037160e+07
2021-11-25T01:00:00.000,  5.93940400e+07
2021-11-25T02:00:00.000,  5.99396480e+07
2021-11-25T03:00:00.000,  6.02911660e+07
2021-11-25T04:00:00.000,  5.97998870e+07
2021-11-25T05:00:00.000,  5.95920280e+07
2021-11-25T06:00:00.000,  5.95920280e+07
2021-11-25T07:00:00.000,  6.00553450e+07
2021-11-25T08:00:00.000,  5.97454380e+07
2021-11-25T09:00:00.000,  6.28739990e+07
2021-11-25T10:00:00.000,  6.61688440e+07
2021-11-25T11:00:00.000,  6.49791530e+07
2021-11-25T12:00:00.000,  6.41498080e+07
2021-11-25T13:00:00.000,  6.53721740e+07
2021-11-25T14:00:00.000,  6.47625610e+07
2021-11-25T15:00:00.000,  8.04657970e+07
2021-11-25T16:00:00.000,  3.32752905e+08"""

# this looks bad without the last ^^


# last the remove  one -> it is great


df_0 = pd.read_csv(io.StringIO(data_0))
df_0 = df_0.astype({'time': 'datetime64[ms]'})

ax1 = fplt.create_plot("improper plot problem", rows=1, maximize=False)

plot1 = fplt.plot(df_0["time vol".split()], ax=ax1, legend="test1")

plot1.update_data(df_0["time vol".split()], gfx=False)

plot1.update_gfx()

fplt.show()`

**Comment by highfestiva** [comment]
Hi Jon, I had a hard time finding the bug, but eventually I got it. Try 62ee4b1.

**Comment by jonsl** [comment]
Good Man, very good.
I'm gonna talk to you again :+1:
