### ISSUE TITLE
[BUG] finplot will not install

### ISSUE THREAD

**Issue by DcPublished** [highfestiva/finplot#314]
### Requirements (place an `x` in each of the `[ ]`)**
* [ x] I realize finplot is not a web lib. (Hint: it's native!)
* [ x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [ x] I've searched for any related issues and avoided creating a duplicate issue.
* [ x] I've updated finplot (`pip install -U finplot`).
* [ x] I've supplied the required data to run my code below.

### Code to reproduce
At terminal: 
pip3 install -U finplot

### Describe the bug
When attempting to install finplot using the code above, it throws this error: 
danieltclark@Daniels-MacBook-Pro-2 ~ % pip3 install finplot
Collecting finplot
  Using cached finplot-1.8.1-py3-none-any.whl (32 kB)
Collecting pandas
  Downloading pandas-1.4.2-cp39-cp39-macosx_11_0_arm64.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 32.3 MB/s eta 0:00:00
Collecting pyqtgraph>=0.11.1
  Using cached pyqtgraph-0.12.4-py3-none-any.whl (995 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/8f/mn693f8d60vd0dt5cv9k0l940000gn/T/pip-build-env-mi6_xuo9/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/private/var/folders/8f/mn693f8d60vd0dt5cv9k0l940000gn/T/pip-build-env-mi6_xuo9/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/8f/mn693f8d60vd0dt5cv9k0l940000gn/T/pip-build-env-mi6_xuo9/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 594, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/8f/mn693f8d60vd0dt5cv9k0l940000gn/T/pip-build-env-mi6_xuo9/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/8f/mn693f8d60vd0dt5cv9k0l940000gn/T/pip-build-env-mi6_xuo9/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 241, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/8f/mn693f8d60vd0dt5cv9k0l940000gn/T/pip-build-env-mi6_xuo9/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Expected behavior
finplot installs successfully

#### Reproducible in:

*OS*: macOS Monterey 12.3.1
*finplot version*: 1.8.1
*pyqtgraph version*: 0.12.4
*pyqt version*: Error: "No matching distribution for pyqt"

**Comment by DcPublished** [comment]
I forgot to mention that I'm trying to load finplot on a MacBook M1 Max.   

The finplot install is NOT a native M1 app.   I was forced to install this as a rosetta-based app.   I'm still seeing errors with finplot.

Although I want to exclude weekend data, I now have serious doubts that finplot will handle the high volume of data the app will be processing.

**Comment by highfestiva** [comment]
Unfortunately I don't have Mac myself, and there are no other willing maintainers. I use finplot for 1M candlesticks, but that's pushing the envelope (and some operations are annoyingly slow).
