### ISSUE TITLE
Plot renko with csv file

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#323]
Hi, I use the 'renko-dark-mode.py' code in the example to plot the renko diagram, and I use the CSV file download from yahoo finance website. I got an error:

```
Traceback (most recent call last):
  File "M:/renko.py", line 19, in <module>
    plot = fplt.renko(df[['Close','Volume']], ax=ax) # let renko transform volume by passing it in as an extra column
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['Volume'] not in index"
```

I have changed the 'Date' column of the CSV file to 'timedate' format and set it to the index, the error still exists, I have set the 'Date' and 'Volume' to double index again, still not working. What should I do because of this?

```
import finplot as fplt
import pandas as pd
#import yfinance as yf
#df = yf.download('BNO', '2014-01-01',proxy="127.0.0.1:1080")

df = pd.read_csv('i:\\BNO.csv')
df['Date'] = pd.to_datetime(df.Date)
#df.set_index('Date', inplace = True)
df.set_index(['Date', 'Volume'],inplace = True)

w = fplt.foreground = '#eef'
b = fplt.background = fplt.odd_plot_background = '#242320'
fplt.candle_bull_color = fplt.volume_bull_color = fplt.candle_bull_body_color = fplt.volume_bull_body_color = '#352'
fplt.candle_bear_color = fplt.volume_bear_color = '#810'
fplt.cross_hair_color = w+'a'

# plot renko + renko-transformed volume
ax,axv = fplt.create_plot('US Brent Oil Renko [dark mode]', rows=2, maximize=False)
plot = fplt.renko(df[['Close','Volume']], ax=ax) # let renko transform volume by passing it in as an extra column
df_renko = plot.datasrc.df # names of new renko columns are time, open, close, high, low and whatever extras you pass in
fplt.volume_ocv(df_renko[['Date','open','close','Volume']], ax=axv)
fplt.show()
```

```
>>> df
                         Open       High        Low      Close  Adj Close
Date       Volume                                                        
2021-04-20 1049100  16.980000  17.010000  16.530001  16.760000  16.760000
2021-04-21 941000   16.450001  16.709999  16.379999  16.389999  16.389999
2021-04-22 666700   16.570000  16.570000  16.350000  16.530001  16.530001
2021-04-23 636300   16.450001  16.700001  16.430000  16.650000  16.650000
2021-04-26 639200   16.379999  16.639999  16.370001  16.559999  16.559999
...                       ...        ...        ...        ...        ...
2022-04-12 1559600  29.510000  30.070000  29.510000  29.820000  29.820000
2022-04-13 1397900  30.430000  31.040001  29.980000  31.010000  31.010000
2022-04-14 1722200  30.629999  32.000000  30.559999  31.700001  31.700001
2022-04-18 1228200  32.200001  32.709999  31.969999  32.220001  32.220001
2022-04-19 1886100  31.219999  31.219999  30.459999  30.620001  30.620001
```

**Comment by highfestiva** [comment]
You should append a .zip file containing minimal code and data so I can test it myself.

**Comment by sunjar2020** [comment]
> You should append a .zip file containing minimal code and data so I can test it myself.

Ok, here is the zip file download link, thank you.

https://xfl.jp/CRWJ9K

**Comment by highfestiva** [comment]
Two errors:
1. `df.set_index('Date',inplace = True)`
2. `fplt.volume_ocv(df_renko[['time','open','close','Volume']], ax=axv)`

Regarding the second one, `finplot` internally renames the first five columns to `time open close high low` (to compensate for crappy names such as `0 1 2 3 4`).

**Comment by sunjar2020** [comment]
> 

Nailed it. Thank you very much.
