### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gabrsafwat** [highfestiva/finplot#380]
When I run most of the examples on PyCharm I get this error message:

```
Traceback (most recent call last):
  File "C:\PyProjects\stockScreener\ui_files\chart.py", line 6, in <module>
    fplt.show()
  File "C:\PyProjects\stockScreener\venv\lib\site-packages\finplot\__init__.py", line 1834, in show
    app = QtGui.QApplication.instance()
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'. Did you mean: 'QGuiApplication'?
```

Also, there is no available documentation for this library for users like me who are new to the python environment.

**Comment by highfestiva** [comment]
Newer versions of PyQt are not backwards-compatible. I'll try to fix this in a few days.

**Comment by highfestiva** [comment]
Transitioned to PyQt6 in efb869668b2d0eb35e332eed5fce75f523b8ad0a.
