### ISSUE TITLE
Trying to draw pm/ah squares, attribute error on update

### ISSUE THREAD

**Issue by Camelket** [highfestiva/finplot#61]
Hey I am trying to create a class that draws squares at specific times of day (for me AH/PM) but running into an issue when switching symbols. Not sure if this is proper etiquette to ask this sort of thing in an "issue"

I took the embed example and added, albeit a probably poorly written, class that should and does draw the squares i am looking for. but somehow it messes up updating the price candles.  any pointers would be much appreciated :) 
thank you for all your hard work so far.

here is the error:
Traceback (most recent call last):
  File "path_redacted/example.py", line 159, in update
    plots[0].update_data(price)
  File "path_redacted\finplot.py", line 2188, in _update_data
    li = len(i.datasrc.df)
  File "path_redacted\Anaconda3\envs\finplot_test\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'df'

and the example:

```
from functools import lru_cache
from threading import Thread

import finplot11 as fplt
import pandas as pd
import pyqtgraph as pg
import yfinance as yf
from PyQt5 import QtCore
from PyQt5.QtGui import QApplication, QGridLayout
from PyQt5.QtWidgets import QComboBox, QGraphicsView, QLabel

current_phase = None

class MarketPhasesItem(fplt.FinPlotItem): #datasrc must be in 24hour format, timestamp col must be named "Datetime"
    def __init__(self, ax, datasrc,lod = True, colorfunc=None,draw_pm=True, draw_ah=False, candle_width = 0.6):
        self.ax = ax
        self.draw_pm = draw_pm
        self.draw_ah = draw_ah
        self.colorfunc = colorfunc
        self.candle_width = candle_width
        self.df = datasrc
        self.get_rect_points()
        super().__init__(ax, datasrc, lod)

    def get_rect_points(self):
        if self.draw_pm == True:
            self.pm_x_points = self.getxdataPoints(self.df, "10:00:00", "13:30:00") #changed time for example because yfinance doesnt supply premarket data (would be 04:00:00, 09:30:00 otherwise)
            self.pm_y_points = self.getydataPoints(self.df, self.pm_x_points)
        if self.draw_ah == True:
            self.ah_x_points = self.getxdataPoints(self.df, "16:00:00","20:01:00")
            self.ah_y_points = self.getydataPoints(self.df, self.ah_x_points)

    def getxdataPoints(self, datasrc, startTime, endTime):
        if 'Datetime' in self.df.columns.tolist():
            self.df = self.df.set_index("Datetime")
        startEnd = []
        daysorted = [group[1] for group in self.df.groupby([self.df.index.year,self.df.index.month,self.df.index.day])]
        self.dfreset = self.df.reset_index()
        for x in daysorted:
            pm = x.between_time(startTime,endTime, include_end=False)
            pm = pm.sort_index(ascending=True)
            if len(pm.index)>= 3:
                stEn = {}
                indexStart = None
                indexEnd = None               
                start = pm.iloc[0].name
                end = pm.iloc[-1].name
                if start<end:
                    indexStart = self.dfreset.index[self.dfreset["Datetime"] == start]
                    indexEnd = self.dfreset.index[self.dfreset["Datetime"] == end]
                    stEn["start"] = indexStart[0]
                    stEn["end"] = indexEnd[0]
                    startEnd.append(stEn)
        return startEnd

    def getydataPoints(self, datasrc, startEnd, highlow=True):
        self.startEnd = startEnd
        df_reset = self.df.reset_index()
        hilo = []  
        if highlow==True:
            for x in self.startEnd:
                hilodict = {}
                start = x["start"]
                end = x["end"]
                hi = df_reset.loc[start:end]["High"].max()
                lo = df_reset.loc[start:end]["Low"].min()
                hilodict["High"] = hi
                hilodict["Low"]= lo
                hilo.append(hilodict)
        return hilo
        
    def generate_picture(self, boundingRect):
        pmSquarecolor=pg.mkColor("k")
        ahSquarecolor=pg.mkColor(190, 200, 210)
        left,right = boundingRect.left(), boundingRect.right()
        phases=[]
    
        def drawZones(xdataPoints,ydataPoints,color):
            p.setPen(pg.mkPen(None))
            p.setBrush(pg.mkBrush(color))
            rects = []
            if len(xdataPoints)==len(ydataPoints):            
                for x, y in zip(xdataPoints, ydataPoints):
                    scord = x["start"]-(.5)
                    ecord = x["end"]+(.5)
                    hi = y["High"]
                    lo = y["Low"]
                    if scord<=ecord:
                        rect = p.drawRect(QtCore.QRectF(QtCore.QPointF(scord,lo),QtCore.QPointF(ecord,hi)))
                        rects.append(rect)       
            return rects
                
        p = self.painter
        p.begin(self.picture) 
        if self.draw_pm == True:
            phases.append(drawZones(self.pm_x_points,self.pm_y_points, pmSquarecolor))
        if self.draw_ah == True:
            phases.append(drawZones(self.ah_x_points,self.ah_y_points, ahSquarecolor))  
        p.end()
        return phases


app = QApplication([])
win = QGraphicsView()
win.setWindowTitle('TradingView wannabe')
layout = QGridLayout()
win.setLayout(layout)
win.resize(600, 500)

combo = QComboBox()
combo.setEditable(True)
[combo.addItem(i) for i in 'FB GFN REVG TSLA TWTR WMT CT=F GC=F ^FTSE ^N225 EURUSD=X ETH-USD'.split()]
layout.addWidget(combo, 0, 0, 1, 1)
info = QLabel()
layout.addWidget(info, 0, 1, 1, 1)

ax = fplt.create_plot(init_zoom_periods=100)
win.axs = [ax] # finplot requres this property
layout.addWidget(ax.vb.win, 1, 0, 1, 2)


@lru_cache(maxsize=15)
def download(symbol):
    return yf.download(symbol, period = "5d", interval = "1m")

@lru_cache(maxsize=100)
def get_name(symbol):
    return yf.Ticker(symbol).info['shortName']

def create_phases(df):
    global current_phase
    df_copy = df.reset_index().copy()
    phases = MarketPhasesItem(ax = ax, datasrc = df_copy)
    current_phase = phases
    current_phase.setZValue(-10)
    ax.addItem(current_phase)

def update_phases(df):
    global current_phase
    df_copy = df.reset_index().copy()
    ax.removeItem(current_phase)
    phases = MarketPhasesItem(ax = ax, datasrc = df_copy)
    current_phase = phases
    current_phase.setZValue(-10)
    ax.addItem(current_phase)

plots = []
def update(txt):
    global current_phase
    df = download(txt)
    if len(df) < 20: # symbol does not exist
        return
    info.setText('Loading symbol name...')
    price = df['Open Close High Low'.split()]
    if not plots:
        plots.append(fplt.candlestick_ochl(price))
        create_phases(df)
    else:
        plots[0].update_data(price)
        update_phases(df)
    Thread(target=lambda: info.setText(get_name(txt))).start() # slow, so use thread

combo.currentTextChanged.connect(update)
update(combo.currentText())


fplt.show(qt_exec=False) # prepares plots when they're all setup
win.show()
app.exec_()

```

**Comment by highfestiva** [comment]
Almost there. The datasrc that you're supplying to `FinPlotItem`'s constructor is not of the same kind as `PandasDataSource`, it is a pandas `DataFrame`. So do like this instead:

````python
super().__init__(ax, fplt._create_datasrc(ax, datasrc), lod)
````

**Comment by highfestiva** [comment]
@Camelket For some obscure reason you also need `current_phase.repaint()` at the end of `update_phases()`. Which is weird to me, as it was just created...

**Comment by Camelket** [comment]
@highfestiva that solved it, thanks. I was confused by the error appearing in the update_data() function.
The need to call repaint() is weird indeed.
