### ISSUE TITLE
reset_index bug

### ISSUE THREAD

**Issue by wenjinglee** [highfestiva/finplot#81]
in class PandasDataSource, the code ' df = df.reset_index()' will add a new column to df,which will raise some err。
I change the code with ‘df = df.reset_index(drop=True)’,everything is ok!

**Comment by highfestiva** [comment]
That only happens if the index contains timestamps (or at least not is a ranged index). Supply a minimal code example and I'll fix the bug.

**Comment by wenjinglee** [comment]
### **the code is :**

import finplot as fplt
import yfinance
from app.data.data_source import get_hdf5

df = get_hdf5('data/m1_000338.h5', 'm1_000338')
df = df.rename(columns={'eob': 'time'})
print(df.dtypes)
fplt.candlestick_ochl(df[['time','open', 'close', 'high', 'low']])
fplt.show()

### **and the output is :**
symbol               object
frequency            object
open                float64
high                float64
low                 float64
close               float64
volume                int64
amount              float64
bob          datetime64[ns]
time         datetime64[ns]
position              int64
pre_close           float64
dtype: object


Traceback (most recent call last):
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\arrays\datetimelike.py", line 103, in _validate_comparison_value
    other = self._validate_listlike(other, opname, allow_object=True)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\arrays\datetimelike.py", line 852, in _validate_listlike
    f"{opname} requires compatible dtype or scalar, "
TypeError: __le__ requires compatible dtype or scalar, not ndarray

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\arrays\datetimelike.py", line 116, in wrapper
    other = _validate_comparison_value(self, other)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\arrays\datetimelike.py", line 105, in _validate_comparison_value
    raise InvalidComparison(other) from err
pandas.core.arrays.datetimelike.InvalidComparison: [17.93 17.91 17.89 ... 16.1  16.09 16.11]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/quant/projects/pythonProject/app/t3.py", line 12, in <module>
    fplt.show()
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 1576, in show
    _repaint_candles()
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 2060, in _repaint_candles
    _end_visual_update(item)
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 2024, in _end_visual_update
    item.repaint()
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 905, in repaint
    self.paint(self.painter)
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 908, in paint
    self.update_dirty_picture(self.viewRect())
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 917, in update_dirty_picture
    self._generate_picture(visibleRect)
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 922, in _generate_picture
    self.generate_picture(self.cachedRect)
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 958, in generate_picture
    for shadow, frame, body, df_rows in self.colorfunc(self, self.datasrc, df):
  File "D:\quant\projects\pythonProject\finplot\__init__.py", line 1202, in price_colorfilter
    is_up = df[opencol] <= df[closecol]  # open lower than close = goes up
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
    return method(self, other)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\ops\__init__.py", line 370, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\ops\array_ops.py", line 230, in comparison_op
    res_values = op(lvalues, rvalues)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
    return method(self, other)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\arrays\datetimelike.py", line 118, in wrapper
    return invalid_comparison(self, other, op)
  File "D:\quant\pyEnvs\finplot\lib\site-packages\pandas\core\ops\invalid.py", line 34, in invalid_comparison
    raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
TypeError: Invalid comparison between dtype=datetime64[ns] and ndarray

### **is something wrong? thanks a lot~**

**Comment by wenjinglee** [comment]
df[['time','open', 'close', 'high', 'low']] is :
![image](https://user-images.githubusercontent.com/25558368/102776138-2c8f2c00-43c9-11eb-8513-661b53839c37.png)

**Comment by wenjinglee** [comment]
![image](https://user-images.githubusercontent.com/25558368/102776443-b3440900-43c9-11eb-9041-d9447258b879.png)

**Comment by highfestiva** [comment]
To finplot it looks like you're trying to supply additional information. Do this:

````python
df = df.reset_index(drop=True)
fplt.candlestick_ochl(df[['time','open', 'close', 'high', 'low']])
````

**Explanation:** either your index should be a zero-based (range) index. Or it should be a date+time index. An int64 index could be valuable for other purposes (sparse data), but haven't thought that through properly.

**Comment by wenjinglee** [comment]
I put data with datetime index，it work！thank u！

**Comment by wenjinglee** [comment]
the software help me a lot！
